### ISSUE TITLE
Touch events not bound

### ISSUE THREAD

**Issue by gilphilbert** [robinrodricks/vue3-touch-events#1]
Thanks for creating this library - exactly what I was looking for! However, I can't get it working!

I installed using npm (`npm -i -S vue3-touch-events`)

In my main JS file, I have the following:
```javascript
import Vue from 'vue'
import VueRouter from 'vue-router'
import Vue3TouchEvents from 'vue3-touch-events'
...
Vue.use(Vue3TouchEvents)

Vue.use(VueRouter)
...
  new Vue({
    router,
    render: h => h(App)
  }).$mount('#app')
```

Then, in my template I have the following defined:
```vue
<template>
<div :class="{ 'no-controls': this.$route.path==='/' }">
  <div id="content-container" v-touch:swipe.left="doHideMenu" v-touch:swipe.right="doShowMenu">
    <router-view :playback="playback" @showQueue="toggleQueue" ></router-view>
  </div>
  ...
</template>
<script>
...
export default {
  name: 'Main',
  ...
  props: [ 'isLoggedIn' ],
  methods: {
    toggleQueue (fixed = null) {
      this.showQueue = !this.showQueue
    },
    doShowMenu () {true
      this.showMenu = true
    },
    doHideMenu () {
      this.showMenu = false
    }
  }
}
</script>
```

However, the swipe gestures aren't working. When I had a look at the inspector in chrome, I can't see any events bound to the element other than the click and other basic events.

Any idea what I'm doing wrong?

Thanks!

**Comment by gilphilbert** [comment]
I found out what I was doing wrong... I was in the wrong branch of my own repo. Turns out this doesn't work with Vue 2.x ...

**Comment by robinrodricks** [comment]
For vue 2 you can use the older library.. link in the Readme file.
