### ISSUE TITLE
Any news about a 4.1.1 release?

### ISSUE THREAD

**Issue by paulocheque** [robinrodricks/vue3-touch-events#19]
Any news about a 4.1.1 release?

**Comment by robinrodricks** [comment]
Sure, remind me over the weekend.

**Comment by robinrodricks** [comment]
Published. Can you check if it works?

**Comment by Tommytrg** [comment]
It's not working. It broke our app in production and we have to spend a whole day looking for an error in our codebase. Please don't release a new version of a package that people is using if you think it could break something :crying_cat_face:

**Comment by kirbby** [comment]
ye it breaks...

**Comment by robinrodricks** [comment]
Why did you update your production app with new library versions without
testing in dev? But yes I will revert.

**Comment by robinrodricks** [comment]
I only found 2 changes after my first publish

Which one do you think is breaking it?

1
https://github.com/robinrodricks/vue3-touch-events/commit/a86950bbd9d10f903f5c2646acaab7c8d427111e

2
https://github.com/robinrodricks/vue3-touch-events/commit/06d81b843c0bfcbad23c67dfd4eb2647620e46df

**Comment by robinrodricks** [comment]
I have reverted both these commits and republished. Can you guys check and see if it works?

**Comment by kirbby** [comment]
Reverting obviously fixed it. I will check if i find out which of the changes the problem is.

**Comment by kirbby** [comment]
> I only found 2 changes after my first publish
> 
> Which one do you think is breaking it?
> 
> 1. [a86950b](https://github.com/robinrodricks/vue3-touch-events/commit/a86950bbd9d10f903f5c2646acaab7c8d427111e)
> 2. [06d81b8](https://github.com/robinrodricks/vue3-touch-events/commit/06d81b843c0bfcbad23c67dfd4eb2647620e46df)

The correct replacement for `module.exports = { vueTouchEvents }` would be `export default vueTouchEvents`
So basically the version before any changes was the right one. Probably including `"type": "module",` in the package.json.
