### ISSUE TITLE
Module '"vue"' has no exported member 'PluginObject'

### ISSUE THREAD

**Issue by saibbyweb** [robinrodricks/vue3-touch-events#2]
I am using Vue3 + Typescript (Vite), initialising the plugin in `main.ts` like this:

```
import { createApp } from 'vue'
import App from "./App.vue"
import Vue3TouchEvents from "vue3-touch-events";
const app = createApp(App);
app.use(Vue3TouchEvents);
app.mount('#app');
```

Everything works fine in dev, but my builds are failing. I'm getting: 
```
node_modules/vue3-touch-events/index.d.ts:1:9 - error TS2305: 
Module '"vue"' has no exported member 'PluginObject'.

1 import {PluginObject} from "vue";
          ~~~~~~~~~~~~
```

Temporarily, I'm able to fix this by adding a file at `src/types/vue3-touch-events.d.ts` with the following contents:
```
import Vue from "vue";
declare module "vue" {
  export type PluginObject<T> = (app: Vue.App, ...options: any[]) => any;
}
```

Hope it helps.

**Comment by robinrodricks** [comment]
Great thanks. If I make this change in the npm module will it still work?

**Comment by saibbyweb** [comment]
That you'll have to test yourself. Best of luck.

**Comment by alecgibson** [comment]
I've raised https://github.com/robinrodricks/vue3-touch-events/pull/28 to fix this.

In the meantime, the more "accurate" workaround is:

```ts
declare module "vue" {
  export {Plugin as PluginObject} from 'vue';
}
```
