### ISSUE TITLE
SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by phlegx** [robinrodricks/vue3-touch-events#26]
Hi!

I use latest version 4.1.2 with Vite 4.x, vite-ssr and I get this error:

```
[vite] Error when evaluating SSR module /.../vue3/src/main.js: failed to import "/src/common/touch.js"
|- /.../vue3/node_modules/vue3-touch-events/index.js:416
export default vueTouchEvents
^^^^^^

SyntaxError: Unexpected token 'export'
```

If I add `"type": "module",` to package.json of `vue3-touch-events` all works fine again. Can this be added and released please?

Related issue: #23

**Comment by robinrodricks** [comment]
Published, please check?
