### ISSUE TITLE
Issue with the swipe detection logic

### ISSUE THREAD

**Issue by mohsenasm** [robinrodricks/vue3-touch-events#31]
I was reviewing the swipe detection code to better understand its logic. 

In [this line](https://github.com/robinrodricks/vue3-touch-events/blob/aef731a28ab74c65cdbb8b707db66e1f8f5d3b4d/index.js#L218C44-L218C44) we have:
```js
if (distanceY > swipeOutBounded) {
    direction = $this.startY > $this.currentY ? 'top' : 'bottom';
} else {
    direction = $this.startX > $this.currentX ? 'left' : 'right';
}
```
In which the `swipeOutBounded` variable is `$this.options.swipeTolerance`.
Shouldn't it be:
```js
if (distanceY > distanceX) {
    direction = $this.startY > $this.currentY ? 'top' : 'bottom';
} else {
    direction = $this.startX > $this.currentX ? 'left' : 'right';
}
```

In the current code, we are prioritizing top/bottom swipes over left/right swipes. There is no need for prioritization. We can check if the swipe was a more vertical one or a more horizontal one, and make the decision based on that.

For example, if the start point, current point, and swipeTolerance are like this:
```
startX = 0
startY = 0
currentX = 300
currentY = 100
swipeTolerance = 50
```
The current code will set `direction = 'bottom'` instead of `direction = 'right'`.

**Comment by robinrodricks** [comment]
If you feel there is an issue or bug here can you submit a PR I'll check it.

**Comment by mohsenasm** [comment]
Hi @robinrodricks 
I submitted a PR.
I also reported the same issue at https://github.com/jerrybendy/vue-touch-events/issues/100 and it just merged on that repo.

**Comment by robinrodricks** [comment]
Thanks, published.

vue3-touch-events@4.1.6
