### ISSUE TITLE
Types incompatible with Vue 3.4.0+

### ISSUE THREAD

**Issue by kirbby** [robinrodricks/vue3-touch-events#39]
With Vue 3.4.0 and higher there is a type issue for the plugin in the `main.ts`.
`Argument of type '[]' is not assignable to parameter of type 'never'.ts(2345)`
at `app.use(Vue3TouchEvents);`

I just tried to find a fix for a while, but I'm neither a TS wizard nor do I have any experience with creating Vue plugins, so help is appreciated.

**Comment by tjbp** [comment]
Until the types are fixed you can temporarily sort this by passing a type parameter: `app.use<[]>(Vue3TouchEvents);`

**Comment by kirbby** [comment]
Thanks, works like a charm!

**Comment by robinrodricks** [comment]
@stefan-hoelzl  is this correct? https://github.com/robinrodricks/vue3-touch-events?tab=readme-ov-file#typescript-vue-34

**Comment by kirbby** [comment]
This works, thanks!
I wanna emphasize though, that you need to specify an options object, even if you are not passing any options to it, otherwise you still get a Typescript error.
Not working:
`app.use<Vue3TouchEventsOptions>(Vue3TouchEvents)`
Working:
`app.use<Vue3TouchEventsOptions>(Vue3TouchEvents, {})`

Maybe worth noting in the read.me @robinrodricks

Other than that this is resolved and I will close.
